name: canon_microb_rhodopsin
ident: 40
ident_hhsearch: 40
ident_hmmbuild: 30
probab_hhsearch: 95
databases: [ 'uniclust' ]
ref_pdb: 7Z09.A
ref_lysine_pos: 216
pad_n: 14
pad_c: 10
max_missing_n: 10
max_missing_c: 8
min_len: 180
max_rmsd: 3.8
min_align_len: 180
max_align_len: 500
helix_padding_n: 2
helix_padding_c: 2
alphafold_list: workflow/canon_microb_rhodopsin_alphafold.txt
pdb_list: workflow/canon_microb_rhodopsin_pdb.txt
