name: heliorhodopsin
ident: 40
ident_align: 60
ref_pdb: 6SU3.A
ref_lysine_pos: 241
pad_n: 14
pad_c: 10
max_missing_n: 10
max_missing_c: 8
min_len: 180
max_rmsd: 3.8
min_align_len: 180
max_align_len: 500
helix_padding_n: 2
helix_padding_c: 2
alphafold_list: workflow/heliorhodopsin_alphafold.txt
pdb_list: workflow/heliorhodopsin_pdb.txt
